### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [zosiasz/JS2#1]
- [x] usun komentarz z html i dodaj DOCTYPE
- [x] usun dolaczanie styli css, jesli ich nie masz
- [x] w prompt, chyba chcialas napisac zdanie w stylu "podaj swoje imie", zamiast swojego imienia
